### PR TITLE
JFB-5: Bus ticket validator

### PR DESCRIPTION
**Pull request by rtemirbulat**
Task: 
1. Validate each bus ticket, and show warning in case of malicious input
2. Create function to validate bus ticket, show error in the console if 1+ validation rule is violated
3. Output: total tickets, valid tickets, most popular violation
4. Add ability to read tickets from a file
5. Validator - start date can't be in the future
6. Validator - ticket type only day,week,year,month 
7. Validator - price is always even
Rules:
DAY,WEEK,YEAR type can only have start date. Price can't be zero

### CODE REVIEW

**Comment by rtemirbulat** [comment]
Questions that arose while I was doing the task: 
1. Where I should save paths - resources package? Same question for passwords and any secret data, where should I hide it in production code? 
2. I want my loader to create List of types, so I used generics, e.g. List<BusTicket> data, List<ConcertTicket> data, so how should I do it? I have an idea to use ID of ticket types I have (abstract class Ticket UID), then in the JsonDataLoader I should get ID of class Bus Ticket
3. I am creating too many objects when validating to add to List<Error> error, how can I improve? 
4. should I use concurrent hash map with types (BusTicket ticket, Error Type which is enum?)
5. I guess I should create refactoring commits separately from "add function" commits
6. Also I used atomic counter, is it right or not? 
7. I have two exceptions in JsonDataLoader, should I catch them? I created GlobalExceptionHandler and googled that I can handle them with Spring, but how can I actually throw an exception outside of my class? (super?maybe)
8. How to properly handle null value validation and exception? I guess Optional<T> and Logging are the things...

Thank you for your work!

**Comment by deolexx** [comment]
1. you should not store any sensitive information eg: paths, passwords directly  in code or service properties. All this could be sent to your service during startup via environment variables. And should be stored in secured storage like Vault
2. If i understand question correctly than the answer is yes. you should use some generic or interface as type for list 
3. use primitives whenever its possible, try to reuse objects.
4. you should avoid use of concurrency when it is possible cause it's just harder to understand/support etc.
5. this will help to track changes in future  but normally it is depends on agreement within  each team. 
6. There just no sense in atomic so just follow KISS principle and you won't be wrong
7. The idea of global exception handling is that you just could throw exception at any place in your app then catch it in handler and perform some actions rethrow, throw another etc.
8. Right

**Review by deolexx — APPROVED** [review]
LGTM

**Pull request merged**
